# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.4.2
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/unkapp: 604212fad6f24431bd4edc0eb3e50be3f01560f3c416c3c9b0c0b7e71b5583b6
    io.kubernetes.cri-o.SandboxID/unksvr: 604212fad6f24431bd4edc0eb3e50be3f01560f3c416c3c9b0c0b7e71b5583b6
  creationTimestamp: "2025-04-06T13:16:58Z"
  labels:
    app: unk
  name: unkpod
spec:
  containers:
  - args:
    - node
    - main.mjs
    env:
    - name: NO_PROXY
      value: '*.local;169.254/16'
    image: localhost/unksvr:latest
    imagePullPolicy: Never
    name: unksvr
    ports:
    - containerPort: 3000
      hostPort: 8080
  - env:
    - name: NO_PROXY
      value: '*.local;169.254/16'
    image: localhost/unkapp:latest
    imagePullPolicy: Never
    name: unkapp
    securityContext: {}

